dist: trusty
sudo: required
language: java

services:
  - docker

script:
  - set -e
  - docker build -t ${PROJECT}:latest -t ${PROJECT}:$TRAVIS_COMMIT .
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker push ${PROJECT}:latest
  - docker push ${PROJECT}:$TRAVIS_COMMIT


env:
  global:
  - PROJECT=canzea/rpa-listen